image: golang

pipelines:
  pull-requests:
    '**':
      - step:
          caches:
            - gopath
            - gomodules
          script:
            - git config --global url."ssh://git@bitbucket.org".insteadOf "https://bitbucket.org"
            - go get ./...
            - go build ./...
            - go build -tags lambda ./...
            - go vet ./...
            - git clone ssh://git@bitbucket.org/calmisland/go-server-tools
            - go get github.com/calmisland/go-revive
            - go-revive -config go-server-tools/linter/revive.toml -formatter friendly ./src/... || (($? == 2))
            - go get github.com/calmisland/go-junit-report
            - mkdir ./test-reports
            - go test -v ./src/... 2>&1 | go-junit-report -set-exit-code > ./test-reports/junit.xml
definitions:
  caches:
    gopath: ${GOPATH}/src
    gomodules: ${GOPATH}/pkg/mod
